### PR TITLE
README: Add network.trr.custom_uri

### PR DESCRIPTION
**Pull request by olof**
It is my understanding that this only affects the preferences GUI, let me know if that's not the case. (This setting was seen on firefox 68, haven't tried to find out when/how it was introduced.)

@valenting, could you confirm my understanding of this setting? Or set me right! :)

Thanks,

### CODE REVIEW

**Comment by valenting** [comment]
Also a UI preference. Users should not modify it in about:config - it reflects what is set by about:preferences.

**Comment by olof** [comment]
Thanks Valentin. Is

> Modifying this should not be necessary unless you want to update the preferences GUI

fine or should I rephrase as a recommendation not to modify at all?

**Comment by valenting** [comment]
I think it's better not to modify at all, as doing so could break the UI.

**Comment by olof** [comment]
My agenda was to document the undocumented settings, as to avoid confusion when tweaking TRR prefs. By documenting that it is exclusively UI related, most users would not need to modify it. But I struggle to phrase it as a recommendation not to change it at all, as nothing else in the document has that kind of language.

By opening about:config, you would have to agree with the "may break firefox" disclaimer already. What kind of value for custom_uri would break the UI? Would it be more severe than other already documented settings?

Thanks for you feedback :)

**Comment by bagder** [comment]
Thanks!

**Pull request merged**
